### ISSUE TITLE
Online manuscript reproductions not parsed correctly: R label, label language, and url

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#930] opened 2022-04-17 13:13 UTC
Change the `label` of automatically generated R entity holding an online manuscript reproduction (from MSS Google sheet, col. `reproduction_online_url`) from "link" to what follows the instruction, i.e.:
"generate an R entity with label "Reproduction of " + label of the MS (i.e. value in the B column)"
I.e. instead of "link", the label of the R will read e.g. "Reproduction of Paris, Bibliothèque nationale de France, fonds Doat, vol. 21".
Also some other instructions for that col. are not implemented:
- label language of this R = English
- url field is empty instead of holding the hyperlink

![obrazek](https://user-images.githubusercontent.com/55400794/163715779-84501963-cdb5-4ba5-b273-afe631bf14dd.png)

**Comment by tomaham** [comment] 2022-04-18 17:55
Fixed in new import batch (Import batch [development] 2022-04-18 15:57:30.284866)

The link problem for some of the R was caused by different ways of putting the hyperlink to the cell in google sheets. Most of the used formula =HYPERLINK, but some of them used adding a link through the  GS interface. 

Let's use just one way (the HYPERLINK formula).

**Closed** 2022-04-30 13:02 UTC
Labels: bug, data parsing
