### ISSUE TITLE
Allow editors to change entity type

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#765] opened 2022-02-08 16:59 UTC
It sometimes happens that I create something by error under a wrong entity type. Would not the logical option of solving this, rather than removal, be the possibility of changing the entity type in a similar way that things can be created under different entity types - if entity type is not set in suggester dropbox, a box appears to choose entity type?
Main rationale:
Non-admins cannot delete entities (or can they in a new version?), and thus they have no way of removing their error.

**Comment by adammertel** [comment] 2022-02-17 19:52
This is definitely possible and not that complicated. One thing that may happen is that an entity may have some attributes filled that are not relevant for the entity class that is selected (e.g., a Statement is changed to Event and the territory attribute is lost). 
I am not sure how to handle this.

**Comment by davidzbiral** [comment] 2022-02-18 06:17
@adammertel : Let's handle this in a similar way as e.g. Zotero handles Publication type change (e.g. from journal article to book chapter): just give the user a notification that the following attributes will be lost: X, Y, Z. Cancel / Continue.
Let's go forward with this - this is sometimes needed.

**Comment by Ptrhnk** [comment] 2022-05-18 10:26
@davidzbiral After discussion with Adam we allowed changeability to classes V-P-E-G-L-O. There would be to much exceptions for handling change to & from Territory, Statement and also entities that are already usedInStatement and it's not possible to use different class on the same position: e.g. Actions, Concepts etc. 

@adammertel My today's idea is that we can maybe use same boolean as we have for removing entity - allow changeability for some entities when not assigned to statement.

**Comment by adammertel** [comment] 2022-05-18 11:04
@Ptrhnk 
> @adammertel My today's idea is that we can maybe use the same boolean as we have for removing entity - allow changeability for some entities when not assigned to a statement.

What do you think @davidzbiral ? The idea is to let the user change the entity type only in case the entity does not have a direct connection to any statement.

**Comment by davidzbiral** [comment] 2022-05-22 05:20
@adammertel @Ptrhnk:
The usual workflow is that the user creates the entity from Suggester, and thus any entity newly created is already used in a statement. I.e., allowing to change only an unused one does not seem as good design. Can you remind me what happens if an entity used somewhere is removed by "remove", i.e. whether its use is checked, and if a used entity can be removed, what happens to the slots in statements and props in which it was used? 

Removal would be enough, but it is inaccessible to non-admins, that's the problem. We don't want mistaken entities not yet in use to remain in the db, not even as discouraged.

Perhaps we could think outside of the box and instead of entity type change, allow editors to remove entities if they were created in the last 10 minutes or something like that?

**Comment by adammertel** [comment] 2022-05-22 11:52
@davidzbiral 
> Can you remind me what happens if an entity used somewhere is removed by "remove"
Entity used somewhere cannot be removed now.

> allow even editors to remove entities, but only if they were created in the last 10 minutes
I am not completely sure, but it is probably a bad idea. I am not concern of a similar behaviour in any other application, so I would say that there is a reason to that. 

David, I think that the main problem here is not to change entity from P to G even if you have few S, where you used this entity and used a P for the initialization. The problem is e.g., to create a T, add few S and then change the T to P. This may break the whole application.

**Comment by davidzbiral** [comment] 2022-05-22 20:07
@adammertel: I think that removing the erroneous entity would indeed be better than having entity type change. But how to do it while still restricting entity removal - not allowing a regular editor to remove entities? If we solve this, I will withdraw this request.

**Comment by Ptrhnk** [comment] 2022-05-31 10:29
Changeability allowed only for V-P-E-G-L-O entities.

**Closed** 2022-05-31 10:30 UTC
Labels: data model, gui
