### ISSUE TITLE
Slow response prevents processes from finishing if leaving a statement 

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2093] opened 2024-04-26 13:39 UTC
If I select a different elvl, I must wait for db fetch, if I don't and return on the statement, I see that the original incorrect one was kept, i.e. the process does not finish at the background.

Possibility to either solve by the application's different process management, or by speeding up the app (cloud solution?) to remove the cause.

**Comment by Ptrhnk** [comment] 2024-04-29 11:30
@davidzbiral Can you please make some video how you "return on the statement".
The concept is currently that we save data in editor in batches and the save is triggered either when you stop editing or when you leave editor to any direction with your mouse which is what we count on.
So I need to see which way you manage to return on the statement without leaving editor.
At least until we implement other solution, you can use this to save the data instantly:


https://github.com/DISSINET/InkVisitor/assets/29732281/806da82a-e792-4d0c-b986-13c11a84eecb

**Comment by davidzbiral** [comment] 2024-04-30 10:42
We like the elvl switching without reloading, but we need that when then we go to another statement, the elvl value is actually saved.

**Comment by adammertel** [comment] 2024-04-30 18:25
@davidzbiral There should not be a change made by users that has not been saved (except that there is a BE problem). Therefore, this issue is probably caused by a slow response from the server when the Statement is saved. The speed of this request has been improved significantly in the last version so please recheck and close the issue if this is not a problem anymore.

**Comment by davidzbiral** [comment] 2024-05-01 08:00
@adammertel I tested this morning and haven't observed the issue - but it is calm time, DISSINET users not intensely working as last week.

**Closed** 2024-05-01 08:01 UTC
Labels: server, gui, priority
