### ISSUE TITLE
Entity tag too far from mouse cursor

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#935] opened 2022-04-18 13:10 UTC
When you DnD, the entity tag is too far from mouse symbol. The intuition of the user is to have both very close, and thus dropping the entity tag in a field is the same as having the cursor there. Now you need to pay more attention to where the mouse cursor is than where the entity tag is, because they are very far from one another.

![obrazek](https://user-images.githubusercontent.com/55400794/163812872-a80f1694-46e2-4a6c-a635-70a06dc5d340.png)

**Comment by Ptrhnk** [comment] 2022-04-18 15:06
This is weird, should not happen ever. Would be nice to have photo / video ideally of whole screen. Does it happen on monitor or small notebook screen. Do you see all boxes when this happens? (When screen is smaller 1400px there is horizontal scroll activated and layout behaves in different way). Only thing that comes on my mind is something with layout calculations, but can't imagine this happening. Also I would like to now if you test on staging or where do you do it. Not sure if you answered somewhere.

**Comment by Ptrhnk** [comment] 2022-04-18 15:07
Also I added video to #933 where tags are under mouse. I'm curious what is happening.

**Comment by Ptrhnk** [comment] 2022-04-21 08:37
https://user-images.githubusercontent.com/29732281/164415055-1fb0a6eb-9f68-4dbb-b96f-38bf524fdf44.mov

@davidzbiral Same as in #933 -  tested in firefox and chrome on staging, can I close it or is it persisting?

**Comment by davidzbiral** [comment] 2022-04-21 11:05
@Ptrhnk : The video is how it should work, but it does not for me. Perhaps the distance is smaller now but the tag and the cursor are still about 2 cm away.
Latest Firefox (or almost) on v. 1.2.0 | data-import | built: Mon 18.04.2022 19:17.

**Comment by Ptrhnk** [comment] 2022-04-21 11:08
But the video is from the same version same browser. (I didn't change anything)

**Comment by adammertel** [comment] 2022-04-27 19:53
@davidzbiral I am also not able to reproduce this problem. 
I see you probably zoomed in in the browser. Could you maybe try to zoom back to the default 100% to check whether this problem persists?
You said that the distance between the mouse cursor and the Dragged Entity Tag is around 2cm - but which position is reflected on the drop function? Maybe if it works with the Entity position, we can make the dragged Entity Tag more dominant (and maybe dim the cursor) so that the user can focus only on the position of the Entity Tag?

**Comment by davidzbiral** [comment] 2022-04-30 12:38
@Ptrhnk , @adammertel : the bug observed at 120% screen. At 100% screen it disappears. It is even more than 2 cm. We must fix it - some people will want to work on resized screens. It is even more, ca. 5 cm, at 120%.
![inkv-entity-tag-DnD-vs-cursor](https://user-images.githubusercontent.com/55400794/166105939-ea444fbd-8ec7-4628-9ddd-90e292cdf6ea.gif)

**Comment by Ptrhnk** [comment] 2022-04-30 12:43
But resized screen is not standard browser behavior. I would suggest to ban resizing and solve it by user interface design. Resizing screen is just your workaround to some design issue.

**Comment by Ptrhnk** [comment] 2022-04-30 12:49
@davidzbiral we are able to resize design globally from the code on purpose so It's just on further discussion whats the problem and it what cases

**Comment by Ptrhnk** [comment] 2022-04-30 13:05
But still I don't have this problem :D I tried resizing too.

**Comment by Ptrhnk** [comment] 2022-05-03 08:31
@davidzbiral Okay, after further examination I found that it's the problem of DnD library we use in firefox zoom.
It's possible to replicate also on their own example (it behaves differently on firefox zoom settings)
https://react-dnd.github.io/react-dnd/examples/tutorial
Solution is to choose different DnD library but I'm not sure if there is some that can fit all our requirements.
And refactoring to different library would be very hard to implement (still possible). Other possibility is as mentioned above to fit design differently for different resolutions.

**Comment by adammertel** [comment] 2022-05-06 17:16
After discussion with @Ptrhnk, we suggested solving this problem by implementing custom zooming.
This issue is closed in favor of this #935

**Closed by adammertel** 2022-05-06 17:16 UTC
Labels: enhancement, question, priority

**Comment by Ptrhnk** [comment] 2022-05-06 17:59
Official issue by DnD creators
https://github.com/DestinyItemManager/DIM/issues/8328

**Comment by davidzbiral** [comment] 2022-05-09 12:40
@adammertel, @Ptrhnk : OK, let us try to implement a nice custom zooming option to the application.
Please note that depending on eyes tiredness, the same person needs another level of zoom - but if there is a +- button, it's fine.
