### ISSUE TITLE
On laptop restart, undefined errors in InkV window

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1872] opened 2023-11-02 12:54 UTC
When I wake up the laptop, before reloading the InkV window, multiple error "Something bad happened" appears. (When I reload the window, all is fine, but I want to avoid the error and thus the error message in the first place.)

**Comment by adammertel** [comment] 2023-11-02 18:42
Thanks, David, 
This probably happened because the your internet connection was dead the moment you opened your laptop. This is not a bug or problem with the application, but we agree that the way we inform the user about the situation should be better.  

three new issues were created as the reaction on this problem:

 - https://github.com/DISSINET/InkVisitor/issues/1877
 - https://github.com/DISSINET/InkVisitor/issues/1878
 - https://github.com/DISSINET/InkVisitor/issues/1879

**Comment by jancimertel** [comment] 2023-12-17 19:52
closing the original issue as there are more detailed issues created.

**Closed by jancimertel** 2023-12-17 19:52 UTC
Labels: bug
